service: tinkerbell-server

provider:
  name: aws
  runtime: nodejs10.x
  region: ${file(${self:custom.configureFile}):ENVS.SLS_AWS_REGION}
  profile: ${file(${self:custom.configureFile}):ENVS.SLS_AWS_CRED_PROFILE}


functions:
  register:
    handler: ${self:custom.sourcePath}/handler/register-user.register
    events:
      - http:
          path: register
          method: post

custom:
  configureFile: 'config/config.js'
  sourcePath: 'dist'
  webpack:
    webpackConfig: 'webpack.config.js'
    packager: 'yarn'
    includeModules:
      forceExclude:
        - aws-sdk

plugins:
  - serverless-iam-roles-per-function
  - serverless-offline
  - serverless-webpack
