service: tinkerbell-server

provider:
  name: aws
  runtime: nodejs10.x
  region: ${file(${self:custom.configureFile}):ENVS.SLS_AWS_REGION}
  profile: ${file(${self:custom.configureFile}):ENVS.SLS_AWS_CRED_PROFILE}


functions:
  register:
    handler: ${self:custom.sourcePath}/handler/register-user.register
    events:
      - http:
          path: register
          method: post
    environment:
      DYNAMODB_USER_TABLE_NAME: ${file(${self:custom.configureFile}):ENVS.DYNAMODB_USER_TABLE_NAME}
      S3_CUSTOMER_VOICES_BUCKET_NAME: ${file(${self:custom.configureFile}):ENVS.S3_CUSTOMER_VOICES_BUCKET_NAME}
      AZURE_COGNITIVE_SERVICE_KEY: ${file(${self:custom.configureFile}):ENVS.AZURE_COGNITIVE_SERVICE_KEY}
      AZURE_COGNITIVE_SERVICE_ENDPOINT: ${file(${self:custom.configureFile}):ENVS.AZURE_COGNITIVE_SERVICE_ENDPOINT}
    iamRoleStatementsName: ${self:service}-${self:provider.stage}-register-role
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:PutItem
          - s3:GetObject
        Resource:
          - Fn::GetAtt: [ DynamoDBUsers, Arn ]
          - Fn::Join: ['', [Fn::GetAtt: [ S3BucketCustomerVoices, Arn ], '/*'] ]

  result-getter:
    handler: ${self:custom.sourcePath}/handler/get-result.getResult
    events:
      - http:
          path: note/{uuid}
          method: get
    environment:
      DYNAMODB_HISTORY_TABLE_NAME: ${file(${self:custom.configureFile}):ENVS.DYNAMODB_HISTORY_TABLE_NAME}
    iamRoleStatementsName: ${self:service}-${self:provider.stage}-result-getter-role
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:GetItem
        Resource:
          - Fn::GetAtt: [ DynamoDBHistory, Arn ]

resources:
  Resources:
    DynamoDBUsers:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${file(${self:custom.configureFile}):ENVS.DYNAMODB_USER_TABLE_NAME}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: identificationProfileId
            AttributeType: S
        KeySchema:
          - AttributeName: identificationProfileId
            KeyType: HASH

    DynamoDBHistory:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${file(${self:custom.configureFile}):ENVS.DYNAMODB_HISTORY_TABLE_NAME}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: uuid
            AttributeType: S
        KeySchema:
          - AttributeName: uuid
            KeyType: HASH

    S3BucketCustomerVoices:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${file(${self:custom.configureFile}):ENVS.S3_CUSTOMER_VOICES_BUCKET_NAME}

    S3BucketMeetingRecords:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${file(${self:custom.configureFile}):ENVS.S3_MEETING_RECORDS_BUCKET_NAME}

    S3BucketTranscripts:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${file(${self:custom.configureFile}):ENVS.S3_TRANSCRIPTS_BUCKET_NAME}

custom:
  configureFile: 'config/config.js'
  sourcePath: 'dist'
  webpack:
    webpackConfig: 'webpack.config.js'
    packager: 'yarn'
    includeModules:
      forceExclude:
        - aws-sdk

plugins:
  - serverless-iam-roles-per-function
  - serverless-offline
  - serverless-webpack

package:
  individually: true
