service: tinkerbell-server

provider:
  name: azure
  location: Korea Central
  runtime: nodejs10.x

functions:
  register:
    handler: dist/register-user.register
    events:
      - http: true
        x-azure-settings:
          name: req
          methods:
            - post
          route: register
          authLevel: anonymous

plugins:
  - serverless-azure-functions
  - serverless-offline
  - serverless-webpack